version: 0.1.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: .\Artportalen\Artportalen.csproj
  publish_nuget: true
  verbosity: minimal
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
- path: '*.nupkg'
  name: Nuget
  